-- MySQL Script generated by MySQL Workbench
-- Wed Jan 24 19:55:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_laboratorio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_laboratorio` ;

-- -----------------------------------------------------
-- Schema bd_laboratorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_laboratorio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_laboratorio` ;

-- -----------------------------------------------------
-- Table `bd_laboratorio`.`unidadmedida`
-- -----------------------------------------------------
-- Crear la tabla si no existe
CREATE TABLE IF NOT EXISTS `bd_laboratorio`.`unidadmedida` (
  `idUnidadMedida` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `simbol` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`idUnidadMedida`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 6
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- Insertar datos si no existen
INSERT IGNORE INTO `bd_laboratorio`.`unidadmedida` (idUnidadMedida, name, simbol) VALUES
(1, 'Metro', 'm'),
(2, 'Kilogramo', 'kg'),
(3, 'Segundo', 's'),
(4, 'Litro', 'L'),
(5, 'Unidad', 'U');


-- -----------------------------------------------------
-- Table `bd_laboratorio`.`instrumenttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_laboratorio`.`instrumenttype` (
  `code` VARCHAR(255) NOT NULL,
  `idUnidadMedida` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`code`),
  INDEX `fkUnidadMedida_idx` (`idUnidadMedida` ASC) VISIBLE,
  CONSTRAINT `fkUnidadMedida`
    FOREIGN KEY (`idUnidadMedida`)
    REFERENCES `bd_laboratorio`.`unidadmedida` (`idUnidadMedida`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_laboratorio`.`instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_laboratorio`.`instrument` (
  `serie` VARCHAR(255) NOT NULL,
  `mini` VARCHAR(255) NULL DEFAULT NULL,
  `tole` VARCHAR(255) NULL DEFAULT NULL,
  `descri` VARCHAR(255) NULL DEFAULT NULL,
  `maxi` VARCHAR(255) NULL DEFAULT NULL,
  `idTypeInstrument` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`serie`),
  INDEX `fk_instrument_instrumenttype` (`idTypeInstrument` ASC) VISIBLE,
  CONSTRAINT `fk_instrument_instrumenttype`
    FOREIGN KEY (`idTypeInstrument`)
    REFERENCES `bd_laboratorio`.`instrumenttype` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_laboratorio`.`calibration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_laboratorio`.`calibration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `measuring` INT NULL DEFAULT NULL,
  `serieForeing` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_serieCali_idx` (`serieForeing` ASC) VISIBLE,
  CONSTRAINT `fk_serieCali`
    FOREIGN KEY (`serieForeing`)
    REFERENCES `bd_laboratorio`.`instrument` (`serie`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_laboratorio`.`measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_laboratorio`.`measurement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_measurement` INT NULL DEFAULT NULL,
  `referenceData` VARCHAR(255) NOT NULL,
  `reading` VARCHAR(255) NULL DEFAULT NULL,
  `idCalibration` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCalibration_idx` (`idCalibration` ASC) VISIBLE,
  CONSTRAINT `idCalibration`
    FOREIGN KEY (`idCalibration`)
    REFERENCES `bd_laboratorio`.`calibration` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 320
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
