/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ViewController;
import Controller.CalibrationController;
import Controller.IntrumentsController;
import Model.ColorCelda;
import com.toedter.calendar.JDateChooser;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author james
 */
public class Modulo extends javax.swing.JFrame {

    /**
     * Creates new form Modulo
     */
    public Modulo() {
        initComponents();
        btnDeleteInstru.setEnabled(false);
        setIconImage(new javax.swing.ImageIcon("src/main/resources/images/Logo.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        pTipoDeInstrumento = new javax.swing.JTabbedPane();
        pTipoInstrumento = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtNameForSearch = new javax.swing.JTextField();
        btnPDF = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblListInstruments = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pInstrumento = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        txtMini = new javax.swing.JTextField();
        txtTole = new javax.swing.JTextField();
        txtMaxi = new javax.swing.JTextField();
        txtDescri = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnSaveInstru = new javax.swing.JButton();
        btnCleanInstru = new javax.swing.JButton();
        btnDeleteInstru = new javax.swing.JButton();
        jPanel83 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtSearchInstru = new javax.swing.JTextField();
        btnSearchInstru = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInstru = new javax.swing.JTable();
        pCalibraciones = new javax.swing.JPanel();
        btnSaveMeasurement = new javax.swing.JButton();
        btnCleanMeasurement = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCalibrations = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbNombreInstru = new javax.swing.JLabel();
        pCaliMedidas = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        calibrationTxtNumber = new javax.swing.JTextField();
        calibrationTxtMeasurement = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        calibrationDateChooser = new com.toedter.calendar.JDateChooser();
        calibrationBtnSave = new javax.swing.JButton();
        calibrationBtnClean = new javax.swing.JButton();
        calibrationBtnDelete = new javax.swing.JButton();
        pMediciones = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMeasurement = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtNumberSearch = new javax.swing.JTextField();
        btnPDFCalibration = new javax.swing.JButton();
        btnSearchCalibration = new javax.swing.JButton();
        pAcercaDe = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        unaImageIcon = new javax.swing.JLabel();
        miscTxtTitle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        miscTxtSubtitle = new javax.swing.JLabel();
        miscTxtVersion = new javax.swing.JLabel();
        miscTxtTeam = new javax.swing.JLabel();
        miscTxtNameJ = new javax.swing.JLabel();
        miscTxtNameG = new javax.swing.JLabel();
        miscTxtNameK = new javax.swing.JLabel();
        miscTxtCareer = new javax.swing.JLabel();
        miscTxtInstitution = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        logoImageIcon = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Instrumento"));

        jLabel2.setText("Código");

        jLabel3.setText("Nombre");

        jLabel4.setText("Unidad");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtName))
                .addGap(94, 94, 94)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        jLabel6.setText("Nombre");

        btnSearch.setBackground(new java.awt.Color(51, 51, 255));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Buscar");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnPDF.setText("Reporte");
        btnPDF.setContentAreaFilled(false);
        btnPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPDF.setFocusable(false);
        btnPDF.setIcon(new javax.swing.ImageIcon("src/main/resources/images/pdfMin.png"));

        btnPDF.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnPDF.setPressedIcon(new javax.swing.ImageIcon("src/main/resources/images/pdfMin.png"));

        btnPDF.setRolloverIcon(new javax.swing.ImageIcon("src/main/resources/images/pdfMax.png"));
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNameForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch)
                        .addComponent(txtNameForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        tblListInstruments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblListInstruments);
        if (tblListInstruments.getColumnModel().getColumnCount() > 0) {
            tblListInstruments.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSave.setBackground(new java.awt.Color(0, 204, 0));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClean.setBackground(new java.awt.Color(0, 204, 204));
        btnClean.setForeground(new java.awt.Color(255, 255, 255));
        btnClean.setText("Limpiar");
        btnClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Borrar");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pTipoInstrumentoLayout = new javax.swing.GroupLayout(pTipoInstrumento);
        pTipoInstrumento.setLayout(pTipoInstrumentoLayout);
        pTipoInstrumentoLayout.setHorizontalGroup(
            pTipoInstrumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pTipoInstrumentoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(pTipoInstrumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTipoInstrumentoLayout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClean))
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pTipoInstrumentoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pTipoInstrumentoLayout.setVerticalGroup(
            pTipoInstrumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTipoInstrumentoLayout.createSequentialGroup()
                .addGroup(pTipoInstrumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTipoInstrumentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pTipoInstrumentoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pTipoInstrumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnClean))
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pTipoDeInstrumento.addTab("Tipo de instrumento", pTipoInstrumento);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrumento"));

        jLabel8.setText("Serie");

        jLabel9.setText("Minimo");

        jLabel10.setText("Tolerancia");

        jLabel12.setText("Tipo");

        jLabel13.setText("Maximo");

        txtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieActionPerformed(evt);
            }
        });

        txtMini.setText("0");
        txtMini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiniActionPerformed(evt);
            }
        });

        txtTole.setText("0");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setText("Descripcion");

        btnSaveInstru.setBackground(new java.awt.Color(0, 204, 0));
        btnSaveInstru.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveInstru.setText("Guardar");
        btnSaveInstru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveInstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInstruActionPerformed(evt);
            }
        });

        btnCleanInstru.setBackground(new java.awt.Color(0, 204, 204));
        btnCleanInstru.setForeground(new java.awt.Color(255, 255, 255));
        btnCleanInstru.setText("Limpiar");
        btnCleanInstru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnDeleteInstru.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteInstru.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteInstru.setText("Borrar");
        btnDeleteInstru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMini, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTole, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescri, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(txtMaxi, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveInstru)
                    .addComponent(btnDeleteInstru))
                .addGap(30, 30, 30)
                .addComponent(btnCleanInstru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(btnCleanInstru)
                    .addComponent(btnSaveInstru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteInstru))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel83.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        jLabel11.setText("Descripcion");

        btnSearchInstru.setBackground(new java.awt.Color(51, 51, 255));
        btnSearchInstru.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchInstru.setText("Buscar");
        btnSearchInstru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnReport.setText("Reporte");
        btnReport.setContentAreaFilled(false);
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.setFocusable(false);
        btnReport.setIcon(new javax.swing.ImageIcon("src/main/resources/images/pdfMin.png"));

        btnReport.setContentAreaFilled(false);

        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnReport.setPressedIcon(new javax.swing.ImageIcon("src/main/resources/images/pdfMin.png"));

        btnReport.setRolloverIcon(new javax.swing.ImageIcon("src/main/resources/images/pdfMax.png"));

        javax.swing.GroupLayout jPanel83Layout = new javax.swing.GroupLayout(jPanel83);
        jPanel83.setLayout(jPanel83Layout);
        jPanel83Layout.setHorizontalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel83Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtSearchInstru, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(366, 366, 366)
                .addComponent(btnSearchInstru)
                .addGap(18, 18, 18)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel83Layout.setVerticalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel83Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchInstru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchInstru))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel83Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        tbInstru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Serie", "Descripcion", "Minimo", "Maximo", "Tolerancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbInstru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInstruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbInstru);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );

        javax.swing.GroupLayout pInstrumentoLayout = new javax.swing.GroupLayout(pInstrumento);
        pInstrumento.setLayout(pInstrumentoLayout);
        pInstrumentoLayout.setHorizontalGroup(
            pInstrumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInstrumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInstrumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInstrumentoLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pInstrumentoLayout.setVerticalGroup(
            pInstrumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInstrumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pTipoDeInstrumento.addTab("Instrumento", pInstrumento);

        btnSaveMeasurement.setBackground(new java.awt.Color(0, 204, 0));
        btnSaveMeasurement.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveMeasurement.setText("Guardar");
        btnSaveMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveMeasurement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMeasurementActionPerformed(evt);
            }
        });

        btnCleanMeasurement.setBackground(new java.awt.Color(0, 204, 204));
        btnCleanMeasurement.setForeground(new java.awt.Color(255, 255, 255));
        btnCleanMeasurement.setText("Limpiar");
        btnCleanMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        tblCalibrations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Fecha", "Mediciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCalibrations);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrumento"));

        lbNombreInstru.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNombreInstru.setForeground(new java.awt.Color(204, 0, 0));
        lbNombreInstru.setText("Sin instrumento seleccionado!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(lbNombreInstru, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(396, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(lbNombreInstru)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pCaliMedidas.setBorder(javax.swing.BorderFactory.createTitledBorder("Calibración"));

        jLabel21.setText("Número");

        jLabel22.setText("Mediciones");

        calibrationTxtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calibrationTxtNumberActionPerformed(evt);
            }
        });

        jLabel23.setText("Fecha");

        calibrationDateChooser.setDateFormatString("dd/MM/yyyy");
        calibrationDateChooser.setMaxSelectableDate(new java.util.Date());
        calibrationDateChooser.setMinSelectableDate(new java.util.Date(315558093000L));

        calibrationBtnSave.setBackground(new java.awt.Color(0, 204, 0));
        calibrationBtnSave.setForeground(new java.awt.Color(255, 255, 255));
        calibrationBtnSave.setText("Guardar");
        calibrationBtnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calibrationBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calibrationBtnSaveActionPerformed(evt);
            }
        });

        calibrationBtnClean.setBackground(new java.awt.Color(0, 204, 204));
        calibrationBtnClean.setForeground(new java.awt.Color(255, 255, 255));
        calibrationBtnClean.setText("Limpiar");
        calibrationBtnClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        calibrationBtnDelete.setBackground(new java.awt.Color(255, 0, 0));
        calibrationBtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        calibrationBtnDelete.setText("Borrar");
        calibrationBtnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pCaliMedidasLayout = new javax.swing.GroupLayout(pCaliMedidas);
        pCaliMedidas.setLayout(pCaliMedidasLayout);
        pCaliMedidasLayout.setHorizontalGroup(
            pCaliMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCaliMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCaliMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pCaliMedidasLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calibrationTxtMeasurement))
                    .addGroup(pCaliMedidasLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calibrationTxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pCaliMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCaliMedidasLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calibrationDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCaliMedidasLayout.createSequentialGroup()
                        .addComponent(calibrationBtnSave)
                        .addGap(18, 18, 18)
                        .addComponent(calibrationBtnClean)
                        .addGap(18, 18, 18)
                        .addComponent(calibrationBtnDelete)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pCaliMedidasLayout.setVerticalGroup(
            pCaliMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCaliMedidasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pCaliMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCaliMedidasLayout.createSequentialGroup()
                        .addComponent(calibrationDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pCaliMedidasLayout.createSequentialGroup()
                        .addGroup(pCaliMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(calibrationTxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(pCaliMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(calibrationTxtMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calibrationBtnSave)
                            .addComponent(calibrationBtnClean)
                            .addComponent(calibrationBtnDelete))
                        .addGap(12, 12, 12))))
        );

        pMediciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Mediciones"));

        tblMeasurement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medida", "Referencia", "Lectura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMeasurement.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblMeasurement);

        javax.swing.GroupLayout pMedicionesLayout = new javax.swing.GroupLayout(pMediciones);
        pMediciones.setLayout(pMedicionesLayout);
        pMedicionesLayout.setHorizontalGroup(
            pMedicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMedicionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMedicionesLayout.setVerticalGroup(
            pMedicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMedicionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        jLabel16.setText("Número");

        txtNumberSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberSearchActionPerformed(evt);
            }
        });

        btnPDFCalibration.setIcon(new javax.swing.ImageIcon("src/main/resources/images/pdfMin.png"));
        btnPDFCalibration.setText("Reporte");
        btnPDFCalibration.setContentAreaFilled(false);
        btnPDFCalibration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPDFCalibration.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPDFCalibration.setRolloverIcon(new javax.swing.ImageIcon("src/main/resources/images/pdfMax.png"));
        btnPDFCalibration.setSelectedIcon(new javax.swing.ImageIcon("src/main/resources/images/pdfMin.png"));
        btnPDFCalibration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFCalibrationActionPerformed(evt);
            }
        });

        btnSearchCalibration.setBackground(new java.awt.Color(51, 51, 255));
        btnSearchCalibration.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCalibration.setText("Buscar");
        btnSearchCalibration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtNumberSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchCalibration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPDFCalibration)
                .addGap(189, 189, 189))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumberSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btnSearchCalibration))
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(btnPDFCalibration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pCalibracionesLayout = new javax.swing.GroupLayout(pCalibraciones);
        pCalibraciones.setLayout(pCalibracionesLayout);
        pCalibracionesLayout.setHorizontalGroup(
            pCalibracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCalibracionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCalibracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pCalibracionesLayout.createSequentialGroup()
                        .addGroup(pCalibracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCalibracionesLayout.createSequentialGroup()
                                .addComponent(pCaliMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(pMediciones, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pCalibracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCleanMeasurement)
                            .addComponent(btnSaveMeasurement))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCalibracionesLayout.setVerticalGroup(
            pCalibracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCalibracionesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pCalibracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCalibracionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pCalibracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pCaliMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pMediciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pCalibracionesLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnSaveMeasurement)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleanMeasurement)))
                .addGap(22, 22, 22)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pTipoDeInstrumento.addTab("Calibraciones", pCalibraciones);

        ImageIcon imageUna = new ImageIcon("src/main/resources/images/Una.png");
        unaImageIcon.setIcon(imageUna);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unaImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(unaImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        miscTxtTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        miscTxtTitle.setText("Proyecto 1");

        miscTxtSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        miscTxtSubtitle.setText("Sistema de Instrumentos para Laboratorio");

        miscTxtVersion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miscTxtVersion.setText("Versión: 1.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(miscTxtSubtitle)
                .addGap(15, 15, 15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miscTxtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miscTxtSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(miscTxtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        miscTxtTeam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miscTxtTeam.setText("Integrantes:");

        miscTxtNameJ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miscTxtNameJ.setText("James Rivera Nuñez");

        miscTxtNameG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miscTxtNameG.setText("Gabriel Madrigal Castro");

        miscTxtNameK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miscTxtNameK.setText("Kevin Fallas Chavarría");

        miscTxtCareer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miscTxtCareer.setText("EIF206 - Programación III");

        miscTxtInstitution.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miscTxtInstitution.setText("Universidad Nacional - Escuela de Informática");

        ImageIcon imageLogo = new ImageIcon("src/main/resources/images/Logo.png");
        logoImageIcon.setIcon(imageLogo);
        logoImageIcon.setText(null);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(logoImageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(logoImageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pAcercaDeLayout = new javax.swing.GroupLayout(pAcercaDe);
        pAcercaDe.setLayout(pAcercaDeLayout);
        pAcercaDeLayout.setHorizontalGroup(
            pAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAcercaDeLayout.createSequentialGroup()
                .addGroup(pAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAcercaDeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(miscTxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAcercaDeLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(miscTxtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(miscTxtNameJ)
                            .addComponent(miscTxtNameG)
                            .addComponent(miscTxtNameK)))
                    .addGroup(pAcercaDeLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(miscTxtCareer))
                    .addGroup(pAcercaDeLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(miscTxtInstitution)))
                .addGap(67, 67, 67)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pAcercaDeLayout.setVerticalGroup(
            pAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAcercaDeLayout.createSequentialGroup()
                .addGroup(pAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAcercaDeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(miscTxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(miscTxtTeam)
                .addGap(18, 18, 18)
                .addComponent(miscTxtNameJ)
                .addGap(18, 18, 18)
                .addComponent(miscTxtNameG, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(miscTxtNameK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(miscTxtInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(miscTxtCareer)
                .addGap(24, 24, 24))
            .addGroup(pAcercaDeLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pTipoDeInstrumento.addTab("Acerca de", pAcercaDe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTipoDeInstrumento)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTipoDeInstrumento))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ViewController viewController;
    CalibrationController calibrationController;
    IntrumentsController intrumentsController;
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        viewController.actionPerformed(evt);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFActionPerformed


    private void txtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerieActionPerformed

    private void txtMiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiniActionPerformed

    private void btnSaveInstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInstruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveInstruActionPerformed

    private void tbInstruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInstruMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbInstruMouseClicked


    private void calibrationTxtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calibrationTxtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calibrationTxtNumberActionPerformed

    private void txtNumberSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberSearchActionPerformed

    private void btnPDFCalibrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFCalibrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFCalibrationActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        viewController.actionPerformed(evt);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMeasurementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMeasurementActionPerformed

    private void calibrationBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calibrationBtnSaveActionPerformed

    }//GEN-LAST:event_calibrationBtnSaveActionPerformed

    public ViewController getViewController() {
        return viewController;
    }

    public void setViewController(ViewController viewController) {
        this.viewController = viewController;
    }

    public CalibrationController getCalibrationController() {
        return calibrationController;
    }

    public void setCalibrationController(CalibrationController calibrationController) {
        this.calibrationController = calibrationController;
    }

    public IntrumentsController getIntrumentsController() {
        return intrumentsController;
    }

    public void setIntrumentsController(IntrumentsController intrumentsController) {
        this.intrumentsController = intrumentsController;
    }

    public JButton getBtnClean() {
        return btnClean;
    }

    public void setBtnClean(JButton btnClean) {
        this.btnClean = btnClean;
    }

    public JButton getBtnCleanMeasurement() {
        return btnCleanMeasurement;
    }

    public void setBtnCleanMeasurement(JButton btnCleanMeasurement) {
        this.btnCleanMeasurement = btnCleanMeasurement;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnPDF() {
        return btnPDF;
    }

    public void setBtnPDF(JButton btnPDF) {
        this.btnPDF = btnPDF;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public void setBtnSave(JButton btnSave) {
        this.btnSave = btnSave;
    }

    public JButton getBtnSaveMeasurement() {
        return btnSaveMeasurement;
    }

    public JTable getTblCalibrations() {
        return tblCalibrations;
    }

    public void setTblCalibrations(JTable tblCalibrations) {
        this.tblCalibrations = tblCalibrations;
    }

    public JTable getTblMeasurement() {
        return tblMeasurement;
    }

    public void setTblMeasurement(JTable tblMeasurement) {
        this.tblMeasurement = tblMeasurement;
    }

    public void setBtnSaveMeasurement(JButton btnSaveMeasurement) {
        this.btnSaveMeasurement = btnSaveMeasurement;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public void setBtnSearch(JButton btnSearch) {
        this.btnSearch = btnSearch;
    }

    public JDateChooser getCalibrationDateChooser() {
        return calibrationDateChooser;
    }

    public void setCalibrationDateChooser(JDateChooser calibrationDateChooser) {
        this.calibrationDateChooser = calibrationDateChooser;
    }

    public JTable getTblListInstruments() {
        return tblListInstruments;
    }

    public void setTblListInstruments(JTable tblListInstruments) {
        this.tblListInstruments = tblListInstruments;
    }

    public JTextField getTxtCode() {
        return txtCode;
    }

    public void setTxtCode(JTextField txtCode) {
        this.txtCode = txtCode;
    }

    public JTextField getTxtName() {
        return txtName;
    }

    public void setTxtName(JTextField txtName) {
        this.txtName = txtName;
    }

    public JTextField getTxtNameForSearch() {
        return txtNameForSearch;
    }

    public void setTxtNameForSearch(JTextField txtNameForSearch) {
        this.txtNameForSearch = txtNameForSearch;
    }

    public JTextField getTxtUnit() {
        return txtUnit;
    }

    public void setTxtUnit(JTextField txtUnit) {
        this.txtUnit = txtUnit;
    }

    /*Aqui estan los gets y sets del segundo modulo*/
    public void setTbInstru(JTable tbInstru) {
        this.tbInstru = tbInstru;
    }

    public void setTxtDescri(JTextField txtDescri) {
        this.txtDescri = txtDescri;
    }

    public void setTxtMaxi(JTextField txtMaxi) {
        this.txtMaxi = txtMaxi;
    }

    public void setTxtMini(JTextField txtMini) {
        this.txtMini = txtMini;
    }

    public void setTxtSearchInstru(JTextField txtSearchInstru) {
        this.txtSearchInstru = txtSearchInstru;
    }

    public void setTxtSerie(JTextField txtSerie) {
        this.txtSerie = txtSerie;
    }

    public void setTxtTole(JTextField txtTole) {
        this.txtTole = txtTole;
    }

    public void setCmbType(JComboBox<String> cmbType) {
        this.cmbType = cmbType;
    }

    public void setBtnCleanInstru(JButton btnCleanInstru) {
        this.btnCleanInstru = btnCleanInstru;
    }

    public void setBtnDeleteInstru(JButton btnDeleteInstru) {
        this.btnDeleteInstru = btnDeleteInstru;
    }

    public void setBtnReport(JButton btnReport) {
        this.btnReport = btnReport;
    }

    public void setBtnSaveInstru(JButton btnSaveInstru) {
        this.btnSaveInstru = btnSaveInstru;
    }

    public void setBtnSearchInstru(JButton btnSearchInstru) {
        this.btnSearchInstru = btnSearchInstru;
    }

    public JButton getBtnCleanInstru() {
        return btnCleanInstru;
    }

    public JButton getBtnDeleteInstru() {
        return btnDeleteInstru;
    }

    public JButton getBtnReport() {
        return btnReport;
    }

    public JButton getBtnSaveInstru() {
        return btnSaveInstru;
    }

    public JButton getBtnSearchInstru() {
        return btnSearchInstru;
    }

    public JComboBox<String> getCmbType() {
        return cmbType;
    }

    public JTable getTbInstru() {
        return tbInstru;
    }

    public JTextField getTxtDescri() {
        return txtDescri;
    }

    public JTextField getTxtMaxi() {
        return txtMaxi;
    }

    public JTextField getTxtMini() {
        return txtMini;
    }

    public JTextField getTxtSearchInstru() {
        return txtSearchInstru;
    }

    public JTextField getTxtSerie() {
        return txtSerie;
    }

    public JTextField getTxtTole() {
        return txtTole;
    }

    public JButton getBtnPDFCalibration() {
        return btnPDFCalibration;
    }

    public void setBtnPDFCalibration(JButton btnPDFCalibration) {
        this.btnPDFCalibration = btnPDFCalibration;
    }

    public JButton getBtnSearchCalibration() {
        return btnSearchCalibration;
    }

    public void setBtnSearchCalibration(JButton btnSearchCalibration) {
        this.btnSearchCalibration = btnSearchCalibration;
    }

    public JButton getCalibrationBtnClean() {
        return calibrationBtnClean;
    }

    public void setCalibrationBtnClean(JButton calibrationBtnClean) {
        this.calibrationBtnClean = calibrationBtnClean;
    }

    public JButton getCalibrationBtnDelete() {
        return calibrationBtnDelete;
    }

    public void setCalibrationBtnDelete(JButton calibrationBtnDelete) {
        this.calibrationBtnDelete = calibrationBtnDelete;
    }

    public JButton getCalibrationBtnSave() {
        return calibrationBtnSave;
    }

    public void setCalibrationBtnSave(JButton calibrationBtnSave) {
        this.calibrationBtnSave = calibrationBtnSave;
    }

    public JTextField getCalibrationTxtMeasurement() {
        return calibrationTxtMeasurement;
    }

    public void setCalibrationTxtMeasurement(JTextField calibrationTxtMeasurement) {
        this.calibrationTxtMeasurement = calibrationTxtMeasurement;
    }

    public JTextField getCalibrationTxtNumber() {
        return calibrationTxtNumber;
    }

    public void setCalibrationTxtNumber(JTextField calibrationTxtNumber) {
        this.calibrationTxtNumber = calibrationTxtNumber;
    }

    public JTextField getTxtNumberSearch() {
        return txtNumberSearch;
    }

    public void setTxtNumberSearch(JTextField txtNumberSearch) {
        this.txtNumberSearch = txtNumberSearch;
    }

    public void setLbNombreInstru(JLabel lbNombreInstru) {
        this.lbNombreInstru = lbNombreInstru;
    }

    public JLabel getLbNombreInstru() {
        return lbNombreInstru;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnCleanInstru;
    private javax.swing.JButton btnCleanMeasurement;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteInstru;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnPDFCalibration;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveInstru;
    private javax.swing.JButton btnSaveMeasurement;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchCalibration;
    private javax.swing.JButton btnSearchInstru;
    private javax.swing.JButton calibrationBtnClean;
    private javax.swing.JButton calibrationBtnDelete;
    private javax.swing.JButton calibrationBtnSave;
    private com.toedter.calendar.JDateChooser calibrationDateChooser;
    private javax.swing.JTextField calibrationTxtMeasurement;
    private javax.swing.JTextField calibrationTxtNumber;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbNombreInstru;
    private javax.swing.JLabel logoImageIcon;
    private javax.swing.JLabel miscTxtCareer;
    private javax.swing.JLabel miscTxtInstitution;
    private javax.swing.JLabel miscTxtNameG;
    private javax.swing.JLabel miscTxtNameJ;
    private javax.swing.JLabel miscTxtNameK;
    private javax.swing.JLabel miscTxtSubtitle;
    private javax.swing.JLabel miscTxtTeam;
    private javax.swing.JLabel miscTxtTitle;
    private javax.swing.JLabel miscTxtVersion;
    private javax.swing.JPanel pAcercaDe;
    private javax.swing.JPanel pCaliMedidas;
    private javax.swing.JPanel pCalibraciones;
    private javax.swing.JPanel pInstrumento;
    private javax.swing.JPanel pMediciones;
    private javax.swing.JTabbedPane pTipoDeInstrumento;
    private javax.swing.JPanel pTipoInstrumento;
    private javax.swing.JTable tbInstru;
    private javax.swing.JTable tblCalibrations;
    private javax.swing.JTable tblListInstruments;
    private javax.swing.JTable tblMeasurement;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDescri;
    private javax.swing.JTextField txtMaxi;
    private javax.swing.JTextField txtMini;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameForSearch;
    private javax.swing.JTextField txtNumberSearch;
    private javax.swing.JTextField txtSearchInstru;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTole;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JLabel unaImageIcon;
    // End of variables declaration//GEN-END:variables
}
